### ISSUE TITLE
Broken Link/Canvas and README Not in Sync?

### ISSUE THREAD

**Issue by baspin94** [learn-co-curriculum/python-p4-rest-error-handling#1]
### Canvas Link

https://learning.flatironschool.com/courses/6259/pages/error-handling-in-restful-apis?module_item_id=547407

### Concern

I was going to submit feedback about there being a broken link in the ‘400-Class Codes: Client Errors’ section for the Mozilla documentation. 

When I went to check what line in the README it corresponds to, I saw that it’s not broken in the README, so it looks like Canvas may not be in sync with the README, though I didn't look closely to see if there were any other places where they didn't match up.

**Comment by pgill97** [comment]
Link is working on https://learning.flatironschool.com/courses/6130/pages/error-handling-in-restful-apis?module_item_id=482667
